.env.example
client/Dockerfile
client/package.json
client/src/App.vue
client/src/router/index.ts
client/src/services/authService.ts
client/src/services/axios.ts
client/src/views/CallbackView.vue
client/src/views/SpotifyAuthView.vue
docker-compose.yml
server/Dockerfile
server/app/Controller.py
server/app/models/authCode.py
server/requirements.txt

Implemented a Proof of Concept to:
- login via spotify on frontend
- post code to backend
- request token from spotify

Spotify Auth

---

.gitattributes
server/app/recommender/dataset.csv
server/app/recommender/recommender.py
server/app/recommender/songs_dataset.py
server/app/recommender/tests/recommender_test.py
server/app/recommender/tests/songs_dataset_test.py

Add simple recommender system using cosine similarity to get next N songs, based on a list of songs.
All songs need to be part of a fixed dataset. The dataset I used is: https://www.kaggle.com/datasets/rodolfofigueroa/spotify-12m-songs and contains 1.2m songs with their audio features.
To track the dataset file I used Git LFS, as the file exceeds the allowed GitHub size (dataset has ~300MB size).
This recommender class should be used inside the session manager, to retrieve the list of songs the host selects from.

add song recommender system

---

server/app/controller.py
server/app/models/session.py

closes #66, #67, #50, #44, #45

Session Creation

---

server/app/controller.py

[Guest] Leave Session

---

client/src/assets/main.css
client/src/components/AddMoreSong.vue
client/src/components/PlaylistCreator.vue
client/src/components/SongItem.vue
client/src/components/SongSelector.vue
client/src/composables/useSongs.ts
client/src/views/HomeView.vue

- Refactor create playlist to reusable components
- click search to add more songs (background dimed)
- add song process is the same as when create playlist, multiple add at the same time is supported
- after confirm, the list will be cleared and be able to add more

Add song during session

---

server/app/controller.py
server/app/models/token.py
server/app/service.py
server/requirements.txt

BE Spotipy for Authorization

---

server/app/controller.py
server/app/models/session.py
server/app/models/song.py
server/app/models/song_list.py
server/app/models/user.py
server/app/repository.py
server/app/service.py

user model_validate(object: Record) instead of model_validate_json

[Hotfix] Handling Postgres Record Objects

---

server/app/controller.py
server/app/models/session.py
server/app/repository.py
server/app/service.py

[Host] Session Recommendations

---

client/src/components/AddMoreSong.vue
client/src/components/Flower.vue
client/src/components/MainVisualization.vue
client/src/components/Navigation.vue
client/src/components/Petal.vue
client/src/components/PlaylistCreator.vue
client/src/components/Recommendations.vue
client/src/components/SongFeatureDialog.vue
client/src/components/SongSelector.vue
client/src/components/VisualizationAid.vue
client/src/router/index.ts
client/src/services/sessionService.ts
client/src/services/sessionWebsocketService.ts
client/src/types/Song.ts
client/src/types/SongFeature.ts
client/src/views/HomeView.vue
server/app/models/song.py
server/app/service.py

Related to #59 possibly #54
Linked BE and FE for the main visualization to work with the songs from the database.

Main vis febe (Related to UR06)

---

client/src/components/MobileMainViz.vue
client/src/components/PreviouslyPlayed.vue
client/src/components/SongDetailsPopUp.vue
client/src/views/HomeView.vue

- Vote screen for guest home screen
- Leave the possibility to see previously played table, and adjusted display for mobile
https://github.com/user-attachments/assets/d1f7e64a-81a1-4423-82da-12e18e5cca53

140--mobile-vote-screen

---

server/app/controller.py
server/app/models/session.py
server/app/models/user.py
server/app/service.py

[Guest] Vote on Recommendations

---

client/src/assets/main.css
client/src/components/MainVisualization.vue
client/src/components/SongFeatureDialog.vue
client/src/services/sessionService.ts
client/src/views/HomeView.vue

- Adjust overall display (remove navigation bar, and delete unnecessary margin and padding)
- Add "All feature" chart with legend
- replace previously played
- change hide/show button to arrow like
https://github.com/user-attachments/assets/bea2030e-a565-43fe-8fbb-51bb8eadb1fa

150&151--line chart adjustment

---

server/app/models/session.py
server/app/models/song.py
server/app/repository.py
server/app/service.py

- add field most_significant_feature to song model
- if it is None, song was no recommendation (added manually)
- otherwise str('danceability', 'energy', 'speechiness', 'valence', 'tempo')
- add field similarity_score to song model
- if it is float(-1), song was no recommendation (added manually)
closes #157

157 Most Significant Feature

---

server/app/repository.py
server/app/service.py

- only match beginning of songs
closes #160

160 Better Song Filter

---

server/app/models/song.py
server/app/service.py

164 Record User Who Added Song

---

client/src/services/websocketService.ts
server/app/websocket_service.py

very small ws adjustments

---

server/app/models/song.py
server/app/service.py

- adds field to song model for preview_link
closes #167

167 Preview Link

---

server/app/controller.py
server/app/models/artifact.py

[TEMPORARY] Mocked Artifact Object

---

server/app/models/recommendation.py
server/app/models/session.py
server/app/service.py

- adds timestamp for when recommendations have been created
- adds addedBy and genre for initial songs added when session is created
closes #165

Timestamp for Recommendation Creation

---

server/app/controller.py
server/app/models/recommendation.py
server/app/models/session.py
server/app/service.py

168 Playlist Automation

---

client/src/components/AddMoreSong.vue
client/src/components/Flower.vue
client/src/components/MainVisualization.vue
client/src/components/PlaylistCreator.vue
client/src/components/SongFeatureDialog.vue
client/src/views/HomeView.vue

~ Bloom effect on the circle for current song
- Audio autoplay in order
- Loading icon for add song (also for start session)
**And auto closed after 1.5s**
- Starting session queue fixed

182&183--highlight and preview

---

client/src/components/AddMoreSong.vue
client/src/components/Flower.vue
client/src/components/MainVisualization.vue
client/src/components/MobileMainViz.vue
client/src/components/Recommendations.vue
client/src/services/sessionService.ts
client/src/stores/session.ts
client/src/types/Recommendation.ts
client/src/views/HomeView.vue
server/app/service.py

zoom fix, style fixes, mobile timer, mobile view

---

client/src/components/Flower.vue
client/src/components/MainVisualization.vue
client/src/views/HomeView.vue

- Adding highlight to flower for the selected one
- Enable audio feature after session ended

flower highlight fix

---

server/app/service.py

- tracks all asyncio tasks
- cancels all running tasks on session end

Kill Asyncio Tasks

---

client/src/components/MainVisualization.vue
client/src/components/MobileMainViz.vue
client/src/components/Recommendations.vue
client/src/stores/session.ts
server/app/service.py

Set zoom to center
Add hover with similarity score on lines
Adjust line width based on similarity score
Fix recommendation order
Corrected mobile timer

fix linking, recommendation order, scroll and zoom, mobile timer

---

server/app/service.py

- returns several usernames if several users have added most songs or voted most (str: "max, moritz, ...")
- returns explanatory values for None types

Update Artifact Values

---

server/app/service.py

- adjust to return list[str] for genre

Artifact Quick Fix

---

server/app/repository.py
server/app/service.py

- keeps track of which songs have already been recommended so not recommend them again

Mark Previous Recommendations

---

client/src/components/MainVisualization.vue
client/src/components/Recommendations.vue

adjust line width for more values
